=== dumppool/GameProgrammingGems/游戏编程精粹3光盘代码/01 General Programming/13 Seegert/XML Parser/uidefinitions.dtd
<!ELEMENT UISCREEN (UIBUTTON | UILISTBOX | UITEXT)*>
<!ATTLIST UISCREEN NAME       CDATA #REQUIRED
                   BACKGROUND CDATA #IMPLIED>

<!ELEMENT UIBUTTON (UIEVENT | UITEXTITEM)*>
<!ATTLIST UIBUTTON NAME   CDATA #REQUIRED
                   LEFT   CDATA #IMPLIED
                   RIGHT  CDATA #IMPLIED
                   TOP    CDATA #IMPLIED
                   BOTTOM CDATA #IMPLIED>

<!ELEMENT UIEVENT EMPTY>
<!ATTLIST UIEVENT PARAMETER1  CDATA #IMPLIED
                  PARAMETER2  CDATA #IMPLIED
                  PARAMETER3  CDATA #IMPLIED
                  PARAMETER4  CDATA #IMPLIED
                  ONCLICK     CDATA #IMPLIED
                  ONMOUSEOVER CDATA #IMPLIED
                  ONMOUSEOFF  CDATA #IMPLIED>

<!ATTLIST UIBUTTON NAME   CDATA #REQUIRED
                   LEFT   CDATA #IMPLIED
                   RIGHT  CDATA #IMPLIED
                   TOP    CDATA #IMPLIED
                   BOTTOM CDATA #IMPLIED>


<!ELEMENT UILISTBOX (UIEVENT | UITEXTITEM)*>
<!ATTLIST UILISTBOX NAME   CDATA #REQUIRED
                    LEFT   CDATA #IMPLIED
                    RIGHT  CDATA #IMPLIED
                    TOP    CDATA #IMPLIED
                    BOTTOM CDATA #IMPLIED>

<!ELEMENT UITEXT    (UITEXTITEM)*>
<!ATTLIST UITEXT    NAME   CDATA #REQUIRED
                    LEFT   CDATA #IMPLIED
                    RIGHT  CDATA #IMPLIED
                    TOP    CDATA #IMPLIED
                    BOTTOM CDATA #IMPLIED>

<!ELEMENT UITEXTITEM (#PCDATA)>

=== dumppool/GameProgrammingGems/游戏编程精粹3光盘代码/01 General Programming/13 Seegert/XML Parser/uisample.xml
<?xml version="1.0"?>
<!DOCTYPE UISCREEN SYSTEM "uidefinitions.dtd">

<UISCREEN NAME="screen0" BACKGROUND="screen0_bg.tga">
    <UITEXT NAME="text0" LEFT="10%" RIGHT="90%"
            TOP="10%" BOTTOM="25%">
        <UITEXTITEM>This is the title bar.</UITEXTITEM>
    </UITEXT>
    <UILISTBOX NAME="list0" LEFT="30%" RIGHT="70%"
               TOP="40%" BOTTOM="70%">
        <UITEXTITEM>This is item 1.</UITEXTITEM>
        <UITEXTITEM>This is item 2.</UITEXTITEM>
        <UITEXTITEM>%1001%</UITEXTITEM>
    </UILISTBOX>
    <UIBUTTON NAME="button0" LEFT="40%" RIGHT="60%"
              TOP="80%" BOTTOM="90%">
        <UITEXTITEM>OK</UITEXTITEM>
        <UIEVENT ONCLICK="PushScreen"
                 PARAMETER1="screen1"/>
    </UIBUTTON>
</UISCREEN>
